import { Routes } from '@angular/router';
import { Home } from './home/home';
import { About } from './about/about';
import { ContactComponent } from './contact/contact';
import { Cart } from './cart/cart';
import { EngagementRings } from './engagement-rings/engagement-rings';
import { WeddingBands } from './wedding-bands/wedding-bands';
import { Necklace } from './necklace/necklace';
import { Bracelets } from './bracelets/bracelets';
import { Earrings } from './earrings/earrings';
import { NotFound } from './not-found/not-found';
import { Product1 } from './productViewOwnPage/engagement-rings/product1/product1';
import { Product2 } from './productViewOwnPage/engagement-rings/product2/product2';
import { Product3 } from './productViewOwnPage/engagement-rings/product3/product3';
import { Product4 } from './productViewOwnPage/engagement-rings/product4/product4';
import { Product5 } from './productViewOwnPage/engagement-rings/product5/product5';
import { Product6 } from './productViewOwnPage/engagement-rings/product6/product6';
import { Product7 } from './productViewOwnPage/engagement-rings/product7/product7';
import { Product8 } from './productViewOwnPage/engagement-rings/product8/product8';
import { Product9 } from './productViewOwnPage/engagement-rings/product9/product9';

import { WeddingBandProduct1 } from './productViewOwnPage/wedding-bands/product1/product1';
import { WeddingBandProduct2 } from './productViewOwnPage/wedding-bands/product2/product2';
import { WeddingBandProduct3 } from './productViewOwnPage/wedding-bands/product3/product3';
import { WeddingBandProduct4 } from './productViewOwnPage/wedding-bands/product4/product4';
import { WeddingBandProduct5 } from './productViewOwnPage/wedding-bands/product5/product5';
import { WeddingBandProduct6 } from './productViewOwnPage/wedding-bands/product6/product6';
import { WeddingBandProduct7 } from './productViewOwnPage/wedding-bands/product7/product7';
import { WeddingBandProduct8 } from './productViewOwnPage/wedding-bands/product8/product8';
import { WeddingBandProduct9 } from './productViewOwnPage/wedding-bands/product9/product9';

import { NecklaceProduct1 } from './productViewOwnPage/necklaces/product1/product1';
import { BraceletProduct1 } from './productViewOwnPage/bracelets/product1/product1';
import { EarringProduct1 } from './productViewOwnPage/earrings/product1/product1';
import { EarringProduct2 } from './productViewOwnPage/earrings/product2/product2';
import { EarringProduct3 } from './productViewOwnPage/earrings/product3/product3';

export const routes: Routes = [
  { path: '', redirectTo: '/home', pathMatch: 'full' },
  { path: 'home', component: Home },
  { path: 'about', component: About },
  { path: 'contact', component: ContactComponent },
  { path: 'bag', component: Cart },
  { path: 'engagement-rings', component: EngagementRings },
  { path: 'wedding-bands', component: WeddingBands },
  { path: 'necklaces', component: Necklace },
  { path: 'bracelets', component: Bracelets },
  { path: 'earrings', component: Earrings },
  { path: '1ct-round-cut-solitaire-ring', component: Product1 },
  { path: '1ct-princess-cut-solitaire-ring', component: Product2 },
  { path: '1ct-cushion-cut-solitaire-ring', component: Product3 },
  { path: '1ct-radiant-cut-solitaire-ring', component: Product4 },
  { path: '1ct-oval-cut-solitaire-ring', component: Product5 },
  { path: '1ct-emerald-cut-solitaire-ring', component: Product6 },
  { path: '1ct-heart-cut-solitaire-ring', component: Product7 },
  { path: '1ct-pear-cut-solitaire-ring', component: Product8 },
  { path: '1ct-assher-cut-solitaire-ring', component: Product9 }
  ,{ path: 'wedding-bands-set-a', component: WeddingBandProduct1 }
  ,{ path: 'wedding-bands-set-b', component: WeddingBandProduct2 }
  ,{ path: 'wedding-bands-set-c', component: WeddingBandProduct3 }
  ,{ path: 'wedding-bands-set-d', component: WeddingBandProduct4 }
  ,{ path: 'wedding-bands-set-e', component: WeddingBandProduct5 }
  ,{ path: 'wedding-bands-set-f', component: WeddingBandProduct6 }
  ,{ path: 'wedding-bands-set-g', component: WeddingBandProduct7 }
  ,{ path: 'wedding-bands-set-h', component: WeddingBandProduct8 }
  ,{ path: 'wedding-bands-set-i', component: WeddingBandProduct9 }
  ,{ path: '30ct-tennis-necklace', component: NecklaceProduct1 }
  ,{ path: '30ct-tennis-bracelet', component: BraceletProduct1 }
  ,{ path: 'stud-earrings', component: EarringProduct1 }
  ,{ path: 'cluster-set', component: EarringProduct2 }
  ,{ path: 'oval-cut-green-emerald-earrings', component: EarringProduct3 }
  ,{ path: '**', component: NotFound }
];
